### ISSUE TITLE
A library should never exit() the application

### ISSUE THREAD

**Issue by psychon** [Airblader/xcb-util-xrm#30]
Handling allocation errors by calling `err()` is simple, but bad, e.g. http://stackoverflow.com/questions/14199689/how-can-i-handle-exit-calls-in-3rd-party-library-code http://ubuntuforums.org/showthread.php?t=612606 (random google results).

**Comment by Airblader** [comment]
I agree with the point (and frankly this was just an oversight). But I would guess the same should apply to `assert`, shouldn't it? But AFAIK quite a lot of libraries `assert` in their code (cairo, for example :) ).
