### ISSUE TITLE
Ensure all functions are tested

### ISSUE THREAD

**Issue by Airblader** [Airblader/xcb-util-xrm#46]
We're currently missing tests for

* `xcb_xrm_database_from_file`
* `xcb_xrm_database_from_resource_manager`
* `xcb_xrm_database_from_default`

See #33. Thanks to @psychon for the hint that we can use `AM_TESTS_ENVIRONMENT`.

**Comment by Airblader** [comment]
This sort of depends on #47 .

**Comment by psychon** [comment]
We can also have a shell script as a test that sets up the right environment and then runs the test binary. That way different tests could be run in different environments (AFAIK there is no per-test equivalent for `AM_TESTS_ENVIRONMENT`)

**Comment by Airblader** [comment]
In theory the test could also just call `setenv`, right? The only environment variables we need are `$HOME` and `$XENVIRONMENT` anyway.

**Comment by psychon** [comment]
Oh, right. That's simple.

I was thinking of tests needing an X server, but even that can be done via `xvfb-run` and a some C code setting the right properties.

**Comment by Airblader** [comment]
Right, we'd need that for `RESOURCE_MANAGER`, that I wasn't thinking of. It sounds like these tests should be in a separate test file. It'd be great if we had #49 for this. I tried that before and didn't get it to work due to my lack of knowledge on autoconf etc. If you can provide what's necessary to split tests into multiple files, that would help me out a lot. :)

**Comment by Airblader** [comment]
Some of these are now tested in #53.
