### ISSUE TITLE
*.name  in xresources file is differently parsed with xcb-util-xrm then xlib

### ISSUE THREAD

**Issue by DaveDavenport** [Airblader/xcb-util-xrm#66]
Unsure if this is a xlib not following spec or not, but setting this in RM database:

```
*.dpi:  133
```
and then requesting: `rofi.dpi`  worked.  but not when using xcb-util-xrm.

This test will show it:
```diff
diff --git a/tests/tests_match.c b/tests/tests_match.c
index 345b9ca..e9b45f8 100644
--- a/tests/tests_match.c
+++ b/tests/tests_match.c
@@ -75,6 +75,7 @@ static int test_get_resource(void) {
     err |= check_get_resource("First*?.third: 1", "First.third", "", NULL, false);
     err |= check_get_resource("First: 1", "first", "", NULL, false);
     err |= check_get_resource("First: 1", "", "first", NULL, false);
+    err |= check_get_resource("*.dpi: 133", "rofi.dpi", "rofi.dpi", "133", false);
     /* Duplicate entries */
     err |= check_get_resource(
             "First: 1\n"
```

results in:
```
== Assert that getting resource <rofi.dpi> / <rofi.dpi> returns <133>
xcb_xrm_resource_get_string() returned NULL
Returned NULL, but Xlib returned <133>
```

(original bug [here](https://github.com/DaveDavenport/rofi/issues/423))

**Comment by DaveDavenport** [comment]
Based on [this](https://tronche.com/gui/x/xlib/resource-manager/file-syntax.html) it might be invalid syntax.
```*dpi: 133 ```  seems to work.

**Comment by Airblader** [comment]
That's because the Xresources file is invalid. `*` and `?` are not interchangable elements for matching one versus many, see the [specification](https://tronche.com/gui/x/xlib/resource-manager/file-syntax.html):

````
Binding		=	"." | "*"
Component	=	"?" | ComponentName
```

The asterisk `*` is actually the equivalent of `.`, but `?` is the equivalent of a component name. In other words,

````
*.dpi: 133
```

violated the specification, the correct syntax is

```
*dpi: 133
```

**Comment by DaveDavenport** [comment]
owh collision. thanks for the quick reply. Seems xlib was fuzzy with spec.

**Comment by Airblader** [comment]
Thanks for the report, though. I'm happy to see rofi adapting this library! :-)

**Comment by DaveDavenport** [comment]
Rofi (not its dependencies) are now xlib free :smile:
