### ISSUE TITLE
possibly undefined macro: AC_PROG_LIBTOOL

### ISSUE THREAD

**Issue by WalkerGriggs** [Airblader/xcb-util-xrm#69]
Was working on making this for Deb. Cloned into a clean directory, update the m4 submodule, and ran the autogen. This spit out the error: possibly undefined macro: AC_PROG_LIBTOOL. I got the xorg-macros from xutils-dev so I don't believe there is any problem there.

Perhaps using m4_pattern_allow in the configure is the best way to 'legitimize the token'?

**Comment by psychon** [comment]
Google says you should install libtool.
https://packages.debian.org/stretch/all/libtool/filelist sounds like this will really install some more m4 macros for autotools.

**Comment by Airblader** [comment]
Side question, this library is packaged for Debian already. Why build from source?
