### ISSUE TITLE
xcb-util-xrm package in PPA not working

### ISSUE THREAD

**Issue by TheAtomicGoose** [Airblader/xcb-util-xrm#70]
I'm not 100% sure this is the right place to ask this, but: I'm attempting to install `xcb-util-xrm` on Ubuntu 16.04, and I added the [aguinard PPA](https://launchpad.net/~aguignard/+archive/ubuntu/ppa). Then I ran `sudo apt update`, and finally `sudo apt install xcb-util-xrm`. However, when I ran the final command, I got that the package could not be located...Am I doing something glaringly wrong, or is something up with the PPA? That's the same process I've used for PPAs in the past...

Thanks!

**Comment by Airblader** [comment]
Yeah, that's not an upstream problem, but no worries about that. I don't think I can help you much, though. You should try emailing the PPA maintainer.

**Comment by Airblader** [comment]
Also can you make sure you've added the PPA correctly and that you didn't mistype the package name? Just to rule out the obvious stuff. For the first point you could also try and see if you could install other stuff from that PPA. If apt allows you to list the packages available for a specific PPA you could also check this.

**Comment by psychon** [comment]
Try installing `libxcb-xrm-dev` (or just `libxcb-xrm`, but I doubt you want just this, installing the `-dev`-package will (likely?) install this one, too).
`xcb-util-xrm` is the source package. It contains just source code. From this, the above mentioned two binary packages are built.

**Comment by TheAtomicGoose** [comment]
Sorry for the late response, but @psychon, that worked great. I didn't realize that `xcb-util-xrm` was the source package and not the binary package.
