### ISSUE TITLE
Question: Unset option.

### ISSUE THREAD

**Issue by DaveDavenport** [Airblader/xcb-util-xrm#71]
Is there a way to see if an option is unset?

If I do:
```
rofi.width:
```
It does not find a match when looking it up using: `xcb_xrm_resource_get_string.` (kind of expected)
But is there anyway to see that is specified but not set.

**Comment by Airblader** [comment]
Mhm, I've only looked at the code right now but I think this may be a bug. I would expect that such an entry matches with an entry value. At least that's what I'd expect Xlib to do. I'll have a look at it and push a fix if necessary. 

Can't believe this wasn't in the tests yet.
