### ISSUE TITLE
autogen.sh fail on aarch64 (ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by arcangeli** [Airblader/xcb-util-xrm#74]
Hi,
I've got some trouble installing xcb-xrm on Nvidia Jetson-TX2 running ubuntu 16.04.
`./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
/usr/bin/libtoolize: 1: eval: hookable_fns+=: not found
/usr/bin/libtoolize: 1: eval: hookable_fns+=: not found
/usr/bin/libtoolize: 1: eval: hookable_fns+=: not found
/usr/bin/libtoolize: 1: eval: hookable_fns+=: not found
libtoolize:   error: 'func_options_prep' does not accept hook functions.
autoreconf: libtoolize failed with exit status: 1`

After a fresh git clone and git submodule.
Thanks you in advance.

**Comment by Airblader** [comment]
Looks like something on your system isn't set up correctly regarding building tools.

**Comment by arcangeli** [comment]
I can't resolve this now. But i've compiled from debian souce and it work.
Appologies for this report.
Thanks for your help.
