### ISSUE TITLE
Run the C preprocessor when reading from file

### ISSUE THREAD

**Issue by Airblader** [Airblader/xcb-util-xrm#76]
When we parse a file, we should run the C preprocessor as well. This came up here:

https://www.reddit.com/r/i3wm/comments/76p3tg/color_scheme_not_loading_set_from_resource_upon/

**Comment by psychon** [comment]
Xlib doesn't seem to do this: https://cgit.freedesktop.org/xorg/lib/libX11/tree/src/Xrm.c?id=e835a9dcc3362b5e92893be756dd7ae361e64ced#n1183
```
/* only "include" directive is currently defined */
```

**Comment by Airblader** [comment]
I'm now actually wondering how it could be that the `RESOURCE_MANAGER` property is not yet set when xrdb has terminated. If it closes the connection properly, the events should've been flushed, no? Hm…
