### ISSUE TITLE
Release packages shall include files from git submodules.

### ISSUE THREAD

**Issue by stefanosoffia** [Airblader/xcb-util-xrm#77]
When building from the release packages, the user shall shall not be required to run `git submodule update --init`.

**Comment by Airblader** [comment]
What release packages? The archives Github creates automatically? I don't intend those to be used by anyone, I just can't avoid Github creating them. The correct way to install for non-development purposes is through a package on your distribution.

**Comment by stefanosoffia** [comment]
Thanks for the clarification. I'm not familiar with the GitHub release process. My request stemmed from my attempt to setup `xcb-util-xrm` build with [spack.io](https://spack.io/). I noticed that other related packages, e.g. `xcb-util-cursor`,  `xcb-util-error`, etc., do provide release packages which are self contained. I must admit that those other packages do provide release archives directly on `freedesktop.org` webpage, e.g. https://xcb.freedesktop.org/dist/xcb-util-cursor-0.1.3.tar.gz.

**Comment by Airblader** [comment]
I think we can upload the release package to Github ourselves and that way we can achieve this. I'll look into doing that. :-)

**Comment by stefanosoffia** [comment]
I think I managed to setup the correct checkout steps for `xcb-util-xrm` with Spack (https://github.com/spack/spack/pull/6805/files#diff-3f427155a2027c6e63b7b6098d172b94). Even though this does not seem to be the most common use case, it seems to be supported and as long as everything is automated also on your side I prefer it.

**Comment by Airblader** [comment]
Fair enough, thank you!
