### ISSUE TITLE
anongit xcb-util-common-4 broken?

### ISSUE THREAD

**Issue by zack6849** [Airblader/xcb-util-xrm#78]
Hi There, I'm trying to build this on ubuntu 16.04 because there's no package for it, git fails, but I saw they have http, going to their server here: https://cgit.freedesktop.org/?q=xcb%2Futil-common-m4

and clicking the result comes up 404 not found, so your package won't build for me

Am I doing something wrong?

**Comment by Airblader** [comment]
> git fails

Can you be any more specific than that?

You can see how the package is compiled, say, on Arch [here](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/xcb-util-xrm). I would suggest you look up the package in a later Ubuntu version and see how they build it. I would assume it works the same way.

**Comment by psychon** [comment]
Could this have been a temporary problem with freedesktop.org? I think there were a couple of those recently.

**Comment by zack6849** [comment]
@Airblader it was timing out via git urls, but via http was a 404.

That being said, the link I sent above works now too, so  I guess @psychon was right and it was just a temporary issue.
