### ISSUE TITLE
Cannot clone m4 submodule

### ISSUE THREAD

**Issue by SultanSGillani** [Airblader/xcb-util-xrm#85]
I see a couple of similar issues that are closed however this seems to be an issue again.

running the following shows errors:
```bash
git clone --recursive https://github.com/Airblader/xcb-util-xrm
```
Shows the following error:
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git://anongit.freedesktop.org/xcb/util-common-m4.git' into submodule path '/home/sultan/i3-gaps-deb/xcb-util-xrm/m4' failed
Failed to clone 'm4'. Retry scheduled
Cloning into '/home/sultan/i3-gaps-deb/xcb-util-xrm/m4'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git://anongit.freedesktop.org/xcb/util-common-m4.git' into submodule path '/home/sultan/i3-gaps-deb/xcb-util-xrm/m4' failed
Failed to clone 'm4' a second time, aborting
```
Seems like m4 is not cloeable. Any workarounds? https doesnt work either.

Thanks.

**Comment by psychon** [comment]
Freedesktop's git servers are currently down (according to IRC, they are down for around 15 hours already). If you know some other URL for the git repository, you can follow steps like these to use that git repo instead: https://stackoverflow.com/questions/42028437/how-to-change-git-submodules-url-locally/42035018
(I do not know any alternatively URL for a git repository, sorry.)

**Comment by SultanSGillani** [comment]
Thanks! After looking over your i3-gaps install instructions and installing with debian stretch/buster or ubuntu 19.04, i was able to install without needing to clone and compile xcb-util-xrm which helps my situation.

**Comment by Airblader** [comment]
Thanks from my side as well! I'll close this now since its not our servers :-)

**Comment by psychon** [comment]
Should be fixed now
