### ISSUE TITLE
./install.sh fails on kubuntu 20.10.

### ISSUE THREAD

**Issue by aleemont** [Airblader/xcb-util-xrm#87]
I'm on kubuntu 20.10. When I run `./autogen.sh --prefic=/usr` it shows:
`autoreconf: Entering directory .'`
`autoreconf: configure.ac: not using Gettext`
`autoreconf: running: aclocal `
`configure.ac:16: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd`
`m4/xcb_util_common.m4:8: XCB_UTIL_COMMON is expanded from...`
`configure.ac:16: the top level`
`autoreconf: configure.ac: tracing`
`configure.ac:16: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd`
`m4/xcb_util_common.m4:8: XCB_UTIL_COMMON is expanded from...`
`configure.ac:16: the top level`
`autoreconf: configure.ac: not using Libtool`
`autoreconf: running: /usr/bin/autoconf`
`configure.ac:16: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd`
`m4/xcb_util_common.m4:8: XCB_UTIL_COMMON is expanded from...`
`configure.ac:16: the top level`
`autoreconf: configure.ac: not using Autoheader`
`autoreconf: running: automake --add-missing --copy --no-force`
`configure.ac:16: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd`
`m4/xcb_util_common.m4:8: XCB_UTIL_COMMON is expanded from...`
`configure.ac:16: the top level`
`automake: error: no 'Makefile.am' found for any configure output`
`autoreconf: automake failed with exit status: 1`

**Comment by Airblader** [comment]
Do you have all make dependencies installed, specifically xorg-util-macros?

**Comment by TapZap** [comment]
Recursive cloning of repo, fails. Submodule m4 can't be fetched, tried using git URL and HTTPS URl, neither worked for me.

```
Submodule 'm4' (git://anongit.freedesktop.org/xcb/util-common-m4.git) registered for path 'm4'
Cloning into '/tmp/xcb-util-xrm/m4'...
fatal: unable to access 'https://anongit.freedesktop.org/git/xcb/util-common-m4.git/': Failed to connect to anongit.freedesktop.org port 443: Connection timed out
fatal: clone of 'git://anongit.freedesktop.org/xcb/util-common-m4.git' into submodule path '/tmp/xcb-util-xrm/m4' failed
Failed to clone 'm4'. Retry scheduled
Cloning into '/tmp/xcb-util-xrm/m4'...
fatal: unable to access 'https://anongit.freedesktop.org/git/xcb/util-common-m4.git/': Failed to connect to anongit.freedesktop.org port 443: Connection timed out
fatal: clone of 'git://anongit.freedesktop.org/xcb/util-common-m4.git' into submodule path '/tmp/xcb-util-xrm/m4' failed
Failed to clone 'm4' a second time, aborting
```

```
Submodule 'm4' (git://anongit.freedesktop.org/xcb/util-common-m4.git) registered for path 'm4'
Cloning into '/tmp/test/xcb-util-xrm/m4'...
fatal: unable to access 'https://anongit.freedesktop.org/git/xcb/util-common-m4.git/': Failed to connect to anongit.freedesktop.org port 443: Connection timed out
fatal: clone of 'git://anongit.freedesktop.org/xcb/util-common-m4.git' into submodule path '/tmp/test/xcb-util-xrm/m4' failed
Failed to clone 'm4'. Retry scheduled
```

**Comment by Airblader** [comment]
Did you manually clone the repository? See #86 where someone had a similar issue.

**Comment by TapZap** [comment]
> Did you manually clone the repository? See #86 where someone had a similar issue.

both `https://` and `git://`, does not respond - there is one mirror of freedesktop repo (https://github.com/freedesktop), I'm going to try it, instead of anongit.freedesktop.org.

**Comment by TapZap** [comment]
Ok, now seems like it has been fixed.

**Comment by Airblader** [comment]
Thanks for letting me know. Since the build does work for me I assume this is like the other cases where it's some networking issue and close this.
